name: coaxdrone
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel=6.29.0
  - ipympl=0.9.3
  - matplotlib=3.8.2
  - numpy=1.26.3
  - pyserial=3.5
  - pandas=2.2.0
  - pip=23.3.2
  - scipy=1.12.0
  - pip:
    - pymavlink==2.4.41